### ISSUE TITLE
More users in account collection than listed? 

### ISSUE THREAD

**Issue by zarinekharazian** [gmuric/avax-tweets-dataset#2]
I rehydrated about 5 million tweets from the account collection using Twarc, and am a little confused about the number of unique accounts I am getting. After running 
`users <- unique(as.data.frame(tweets$user_screen_name))
` in R I get 759,548 unique accounts, which is obviously way more than the ~70k you list in the summary statistics for the dataset, and I only hydrated a fraction of the tweet ids. I checked for parsing errors and everything seems ok on that front - any ideas what may be going on?

**Comment by gmuric** [comment]
Hi, thank you for raising this issue. I will need to investigate that. Will get back to you soon

**Comment by gmuric** [comment]
Hi @zkharazian can you provide a bit more details in order to reconstruct this error? We are running some diagnostics at our side and we get the correct number of accounts. Maybe you can share a sample of your parsed CSV together with the Tweet IDs (few thousand) so we could compare it to our data?

**Comment by zarinekharazian** [comment]
Weird, the issue must be on my end then. Here is the first 6000 tweets from my hydrated dataset: [tweets_slice.csv](https://github.com/gmuric/avax-tweets-dataset/files/6504516/tweets_slice.csv)

**Comment by gmuric** [comment]
Thanks! Can you just tell us, what file did you query to get those tweets? 0.txt, 1.txt? It would help us narrow down the problem

**Comment by lishichengyan** [comment]
Hi, thank you for using our data and raising the issue. We checked the [tweets_slice.csv](https://github.com/gmuric/avax-tweets-dataset/files/6504516/tweets_slice.csv) you provided -- 5061 ids can be found in ```0.txt``` and other 4 ids (```1346966906675277824```, ```1332430538741788672```, ```1341579286961123328``` and ```1345446368706514944```) can be found in ```228.txt```, ```254.txt```, ```273.txt``` and ```366.txt```, respectively, however, 935 ids can not be found in our data set. Could you check it on your end? Thanks!

**Comment by zarinekharazian** [comment]
Got it, this must be where I went wrong. I had tried to combine all of the .txt files of ids into one file before hydrating, and I think I messed up this process somewhere.

```
head(listfile_accounts)listfile <- list.files('avax-tweets-dataset/account-tweetids',pattern = "txt",full.names = T, recursive = TRUE)

#extract the  files with folder name tweetids
listfile_accounts <- listfile[grep("tweetids",listfile)]

#combined all the text files in listfile_accounts and store in dataframe 'Data'
for (i in 1:length(listfile_accounts)){
  if(i==1){
    assign(paste0("Data"), read.table(listfile[i],header = FALSE, sep = ","))
  }
  
  if(!i==1){
    
    assign(paste0("Test",i), read.table(listfile[i],header = FALSE, sep = ","))
    Data <- rbind(Data,get(paste0("Test",i)))
    rm(list = ls(pattern = "Test"))
  }
}
```

**Comment by gmuric** [comment]
Please let us know if you make it work. It would be very helpful to catch the bugs early on
