### ISSUE TITLE
Keywords to Tweets Mapping

### ISSUE THREAD

**Issue by sameeravithana** [gmuric/avax-tweets-dataset#4]
Hi, is there a way to map the keywords presented in Table 1 (in the arxiv paper) with the tweet ids?

**Comment by lishichengyan** [comment]
Hi @SamTube405, a quick solution that pops up in my mind would be: 1) leverage the Twitter api to get the complete "Tweet Object" (see: https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/tweet) 2) Match the ```text``` field with these keywords, the ```hashtags``` field would be helpful too (see https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/entities). After that you will have the mapping from keywords to ids. Hope this helps!
