### ISSUE TITLE
Hydrate.py missing?

### ISSUE THREAD

**Issue by dan91** [gmuric/avax-tweets-dataset#5]
Hi! Thanks for this dataset. I'm eager to use it for a research project. Did you maybe forget to push the hydrate.py? Thanks a lot.

**Comment by lishichengyan** [comment]
Hello @dan91 , thanks for raising the issue. We'll provide hydrate.py and keep you updated.

**Comment by lishichengyan** [comment]
Hello @dan91, the hydrate.py is already uploaded to the repo. You can use ```python3 hydrate.py -streaming``` or ```python3 hydrate.py -account``` to hydrate the data now. Should you have any questions, please feel free to raise an issue and we're happy to help! Again, thanks for your interest in our datasets!
